// Auto-generated by transforming erd/data/md/schema/schema.md (the 166-table
// demo dataset) through schemaTextToDocument -> schemaDocumentToText.
// Purely a syntax conversion (SQL DDL -> native ERD DSL) -- no tables added,
// removed, or renamed. See docs/chat/20260726/001-CLAUDE-ERD-EDIT.md for the
// iteration plan this feeds into (Mode: Edit candidate pool).
export const EDIT_CANDIDATE_SCHEMA_TEXT = `
table users {
  id BIGINT pk
  username VARCHAR(50) unique required
  email VARCHAR(100) unique required
  password_hash VARCHAR(255) required
  first_name VARCHAR(50)
  last_name VARCHAR(50)
  role_id BIGINT required -> roles.id
  phone_number VARCHAR(20)
  is_active BOOLEAN
  last_login_at TIMESTAMP
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table roles {
  id BIGINT pk
  name VARCHAR(50) unique required
  description TEXT
  permissions JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table contacts {
  id BIGINT pk
  email VARCHAR(100) required
  phone VARCHAR(20)
  first_name VARCHAR(50)
  last_name VARCHAR(50)
  customer_id BIGINT -> customers.id
  source_channel_id BIGINT -> communication_channels.id
  campaign_id BIGINT -> campaigns.id
  status ENUM('new','qualified','converted','disqualified')
  lead_score DECIMAL(5,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  lead_source VARCHAR(100)
  segment_id BIGINT -> market_segments.id
  acquisition_cost DECIMAL(10,2)
}

table contact_utm_data {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  utm_source VARCHAR(100)
  utm_medium VARCHAR(100)
  utm_campaign VARCHAR(100)
  utm_term VARCHAR(100)
  utm_content VARCHAR(100)
  created_at TIMESTAMP
}

table communication_channels {
  id BIGINT pk
  name VARCHAR(100) required
  type ENUM('social_media','email','messenger','sms','push','call_center','direct') required
  settings JSON
  api_credentials JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  description TEXT
  is_active BOOLEAN
  placement_cost DECIMAL(10,2)
  cost_per_click DECIMAL(10,2)
  responsible_user_id BIGINT -> users.id
}

table messages {
  id BIGINT pk
  subject VARCHAR(255)
  content TEXT required
  title VARCHAR(255)
  description TEXT
  url VARCHAR(255)
  channel_id BIGINT required -> communication_channels.id
  content_type ENUM('email','push','sms','social','in_app') required
  settings JSON
  status ENUM('draft','scheduled','sent','failed')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  scheduled_at TIMESTAMP
  sent_at TIMESTAMP
  campaign_id BIGINT -> campaigns.id
  content_block_id BIGINT -> content_blocks.id
  template_id BIGINT -> message_templates.id
  created_by_user_id BIGINT required -> users.id
}

table message_templates {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  content TEXT required
  content_type ENUM('email','push','sms','social','in_app') required
  variables JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  is_active BOOLEAN
}

table social_media_posts {
  id BIGINT pk
  channel_id BIGINT required -> communication_channels.id
  campaign_id BIGINT -> campaigns.id
  content TEXT required
  media_urls JSON
  published_at TIMESTAMP
  scheduled_at TIMESTAMP
  type ENUM('text','image','video','link','carousel','story') required
  settings JSON
  status ENUM('draft','scheduled','published','failed')
  content_block_id BIGINT -> content_blocks.id
  placement_cost DECIMAL(10,2)
  target_audience_reach INT
  created_by_user_id BIGINT required -> users.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table landing_pages {
  id BIGINT pk
  name VARCHAR(100) required
  url_slug VARCHAR(100) unique required
  type ENUM('product','service','event','lead_capture','promotion') required
  content JSON
  campaign_id BIGINT -> campaigns.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  published_at TIMESTAMP
  is_active BOOLEAN
  creation_cost DECIMAL(10,2)
  seo_title VARCHAR(255)
  seo_description TEXT
  seo_keywords TEXT
  created_by_user_id BIGINT required -> users.id
  header_id BIGINT -> content_blocks.id
  footer_id BIGINT -> content_blocks.id
}

table landing_page_sections {
  id BIGINT pk
  landing_page_id BIGINT required -> landing_pages.id
  content_block_id BIGINT required -> content_blocks.id
  position INT required
  settings JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table content_blocks {
  id BIGINT pk
  name VARCHAR(100) required
  type ENUM('text','image','video','form','header','footer','gallery','testimonial','cta','feature') required
  content JSON required
  settings JSON
  campaign_id BIGINT -> campaigns.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  is_reusable BOOLEAN
  css_class VARCHAR(100)
}

table interactions {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  type ENUM('email_open','email_click','page_visit','form_submit','call','chat','purchase','social_engagement') required
  interaction_time TIMESTAMP required
  interaction_data JSON
  channel_id BIGINT -> communication_channels.id
  landing_page_id BIGINT -> landing_pages.id
  content_block_id BIGINT -> content_blocks.id
  message_id BIGINT -> messages.id
  device_type VARCHAR(50)
  browser VARCHAR(50)
  ip_address VARCHAR(45)
  session_id VARCHAR(100)
  created_at TIMESTAMP
}

table communication_preferences {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  channel_id BIGINT required -> communication_channels.id
  is_subscribed BOOLEAN
  frequency ENUM('daily','weekly','monthly','quarterly','never')
  preferred_time_start TIME
  preferred_time_end TIME
  last_updated TIMESTAMP
}

table audit_logs {
  id BIGINT pk
  entity_type VARCHAR(50) required
  entity_id BIGINT required
  action_type ENUM('create','update','delete','login','logout','export','import') required
  action_time TIMESTAMP
  user_id BIGINT required -> users.id
  previous_state JSON
  new_state JSON
  ip_address VARCHAR(45)
  user_agent TEXT
}

table communication_schedules {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  channel_id BIGINT required -> communication_channels.id
  message_template_id BIGINT required -> message_templates.id
  segment_id BIGINT -> market_segments.id
  frequency ENUM('once','daily','weekly','monthly','custom') required
  cron_expression VARCHAR(100)
  start_date DATE required
  end_date DATE
  active BOOLEAN
  created_by_user_id BIGINT required -> users.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table contact_notes {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  note TEXT required
  created_by_user_id BIGINT required -> users.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table communication_team_members {
  id BIGINT pk
  user_id BIGINT required -> users.id
  channel_id BIGINT required -> communication_channels.id
  role ENUM('manager','content_creator','analyst','support') required
  assigned_at TIMESTAMP
  is_active BOOLEAN
}

table campaigns {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  start_date TIMESTAMP required
  end_date TIMESTAMP
  type ENUM('email','social_media','content','ppc','display','event','integrated') required
  settings JSON
  is_active BOOLEAN
  budget DECIMAL(15,2)
  status ENUM('planned','active','paused','completed','cancelled')
  target_audience_id BIGINT -> target_audiences.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  current_expenses DECIMAL(15,2)
  goals JSON
  parent_campaign_id BIGINT -> campaigns.id
}

table campaign_channels {
  id BIGINT pk
  campaign_id BIGINT required -> campaigns.id
  channel_id BIGINT required -> communication_channels.id
  budget_allocation DECIMAL(15,2)
  start_date TIMESTAMP required
  end_date TIMESTAMP
  kpi_targets JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table funnel_stages {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  order_number INT required
  campaign_id BIGINT -> campaigns.id
  target_conversion_rate DECIMAL(5,2)
  expected_duration INT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  criteria JSON
}

table funnel_transitions {
  id BIGINT pk
  from_stage_id BIGINT -> funnel_stages.id
  to_stage_id BIGINT required -> funnel_stages.id
  contact_id BIGINT required -> contacts.id
  transition_time TIMESTAMP
  campaign_id BIGINT -> campaigns.id
  channel_id BIGINT -> communication_channels.id
  trigger_id BIGINT -> triggers.id
  notes TEXT
}

table triggers {
  id BIGINT pk
  name VARCHAR(100) required
  type ENUM('event','behavior','time','score','manual') required
  conditions JSON required
  next_stage_id BIGINT -> funnel_stages.id
  campaign_id BIGINT -> campaigns.id
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  description TEXT
  priority INT
}

table actions {
  id BIGINT pk
  name VARCHAR(100) required
  type ENUM('send_email','send_sms','create_task','update_contact','webhook','notification','change_stage') required
  settings JSON required
  trigger_id BIGINT required -> triggers.id
  execution_order INT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  description TEXT
  delay_minutes INT
}

table action_executions {
  id BIGINT pk
  action_id BIGINT required -> actions.id
  trigger_id BIGINT required -> triggers.id
  contact_id BIGINT required -> contacts.id
  executed_at TIMESTAMP
  status ENUM('success','failed','pending')
  result JSON
  error_message TEXT
}

table landing_page_metrics {
  id BIGINT pk
  landing_page_id BIGINT required -> landing_pages.id
  date DATE required
  visits INT
  unique_visitors INT
  bounce_rate DECIMAL(5,2)
  avg_time_on_page DECIMAL(10,2)
  conversions INT
  conversion_rate DECIMAL(5,2)
  heatmap_data JSON
  additional_metrics JSON
  source_breakdown JSON
  device_breakdown JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table a_b_tests {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  start_date TIMESTAMP required
  end_date TIMESTAMP
  campaign_id BIGINT -> campaigns.id
  variants JSON required
  status ENUM('draft','running','paused','completed','cancelled')
  winning_variant VARCHAR(100)
  confidence_level DECIMAL(5,2)
  primary_metric VARCHAR(100) required
  secondary_metrics JSON
  traffic_allocation DECIMAL(5,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  entity_type ENUM('landing_page','email','ad','content_block') required
  entity_id BIGINT required
}

table a_b_test_results {
  id BIGINT pk
  test_id BIGINT required -> a_b_tests.id
  variant VARCHAR(100) required
  date DATE required
  impressions INT
  conversions INT
  conversion_rate DECIMAL(5,2)
  metrics JSON
  created_at TIMESTAMP
}

table upsell_opportunities {
  id BIGINT pk
  primary_product_id BIGINT required -> products.id
  upsell_product_id BIGINT required -> products.id
  priority_score DECIMAL(5,2)
  type ENUM('upsell','cross_sell','bundle','add_on') required
  rules JSON
  discount_percentage DECIMAL(5,2)
  display_order INT
  is_active BOOLEAN
  start_date DATE
  end_date DATE
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  success_rate DECIMAL(5,2)
}

table brands {
  id BIGINT pk
  company_id BIGINT required -> companies.id
  name VARCHAR(100) required
  logo_url VARCHAR(255)
  launch_date DATE
  status ENUM('active','inactive','archived')
  description TEXT
  brand_guidelines TEXT
  color_palette VARCHAR(255)
  tagline VARCHAR(255)
  website_url VARCHAR(255)
  social_media_handles JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table brand_4d {
  id BIGINT pk
  brand_id BIGINT required -> brands.id
  dimension_type ENUM('functional','social','mental','spiritual') required
  score INT required
  analysis TEXT
  description TEXT
  strengths TEXT
  weaknesses TEXT
  opportunities TEXT
  threats TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  evaluated_by_user_id BIGINT required -> users.id
}

table market_segments {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  brand_id BIGINT -> brands.id
  geography TEXT
  avg_audience_income DECIMAL(15,2)
  criteria JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  potential_market_size BIGINT
  growth_rate DECIMAL(5,2)
  competition_level ENUM('low','medium','high')
  profitability_index DECIMAL(5,2)
}

table target_audiences {
  id BIGINT pk
  name VARCHAR(100) required
  segment_id BIGINT required -> market_segments.id
  age_min INT
  age_max INT
  gender VARCHAR(20)
  income_level ENUM('low','medium','high','premium')
  psychographics TEXT
  behaviors TEXT
  consumer_habits TEXT
  education_level ENUM('primary','secondary','higher','postgraduate')
  occupation TEXT
  location_targeting JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  estimated_size BIGINT
}

table value_propositions {
  id BIGINT pk
  title VARCHAR(255) required
  description TEXT required
  landing_page_id BIGINT -> landing_pages.id
  campaign_id BIGINT -> campaigns.id
  product_id BIGINT -> products.id
  key_benefits JSON
  supporting_evidence TEXT
  target_audience_id BIGINT -> target_audiences.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  is_active BOOLEAN
}

table customer_journey_maps {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  target_audience_id BIGINT required -> target_audiences.id
  stages JSON required
  touchpoints JSON
  emotions JSON
  pain_points JSON
  opportunities JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table campaign_metrics {
  id BIGINT pk
  campaign_id BIGINT required -> campaigns.id
  date DATE required
  impressions BIGINT
  clicks BIGINT
  conversions INT
  cost DECIMAL(15,2)
  revenue DECIMAL(15,2)
  ctr DECIMAL(5,2)
  cpc DECIMAL(10,2)
  cpa DECIMAL(10,2)
  roas DECIMAL(10,2)
  channel_breakdown JSON
  device_breakdown JSON
  geo_breakdown JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table customer_personas {
  id BIGINT pk
  name VARCHAR(100) required
  target_audience_id BIGINT required -> target_audiences.id
  demographic_details JSON
  goals TEXT
  challenges TEXT
  preferred_channels JSON
  buying_process TEXT
  story TEXT
  avatar_url VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table messaging_frameworks {
  id BIGINT pk
  brand_id BIGINT required -> brands.id
  name VARCHAR(100) required
  target_audience_id BIGINT required -> target_audiences.id
  value_proposition_id BIGINT -> value_propositions.id
  key_messages JSON required
  tone_of_voice TEXT
  dos_and_donts JSON
  examples TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table orders {
  id BIGINT pk
  order_number VARCHAR(50) unique required
  contact_id BIGINT required -> contacts.id
  order_date TIMESTAMP required
  order_total DECIMAL(15,2) required
  tax_amount DECIMAL(15,2)
  shipping_amount DECIMAL(15,2)
  discount_amount DECIMAL(15,2)
  payment_method ENUM('credit_card','bank_transfer','paypal','cash','crypto','other') required
  payment_status ENUM('pending','paid','failed','refunded','partially_refunded')
  order_status ENUM('new','processing','on_hold','completed','cancelled','refunded')
  fulfillment_status ENUM('pending','partial','fulfilled','returned')
  shipping_address_id BIGINT -> addresses.id
  billing_address_id BIGINT -> addresses.id
  campaign_id BIGINT -> campaigns.id
  landing_page_id BIGINT -> landing_pages.id
  channel_id BIGINT -> communication_channels.id
  profit DECIMAL(15,2)
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  customer_po VARCHAR(100)
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table addresses {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  address_type ENUM('shipping','billing','both')
  address_line1 VARCHAR(255) required
  address_line2 VARCHAR(255)
  city VARCHAR(100) required
  state VARCHAR(100)
  postal_code VARCHAR(20)
  country VARCHAR(100) required
  is_default BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table order_items {
  id BIGINT pk
  order_id BIGINT required -> orders.id
  product_id BIGINT required -> products.id
  quantity INT required
  unit_price DECIMAL(15,2) required
  base_price DECIMAL(15,2) required
  discount_amount DECIMAL(15,2)
  discount_percentage DECIMAL(5,2)
  tax_amount DECIMAL(15,2)
  tax_percentage DECIMAL(5,2)
  item_total DECIMAL(15,2) required
  cost_price DECIMAL(15,2)
  profit DECIMAL(15,2)
  upsell_source_id BIGINT -> upsell_opportunities.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  sku VARCHAR(100)
  product_name VARCHAR(255)
  options JSON
  is_digital BOOLEAN
}

table payments {
  id BIGINT pk
  order_id BIGINT required -> orders.id
  amount DECIMAL(15,2) required
  payment_method ENUM('credit_card','bank_transfer','paypal','cash','crypto','other') required
  payment_date TIMESTAMP required
  status ENUM('pending','completed','failed','refunded')
  transaction_id VARCHAR(255)
  payment_details JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  processor_fee DECIMAL(10,2)
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table refunds {
  id BIGINT pk
  order_id BIGINT required -> orders.id
  payment_id BIGINT -> payments.id
  amount DECIMAL(15,2) required
  refund_date TIMESTAMP required
  reason TEXT
  status ENUM('pending','processed','failed')
  refund_transaction_id VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  processed_by_user_id BIGINT -> users.id
  refund_method ENUM('original_payment','store_credit','bank_transfer','other')
}

table marketing_expenses {
  id BIGINT pk
  campaign_id BIGINT -> campaigns.id
  channel_id BIGINT -> communication_channels.id
  date DATE required
  amount DECIMAL(15,2) required
  category ENUM('advertising','content_creation','event','sponsorship','influencer','other') required
  description TEXT
  invoice_number VARCHAR(100)
  vendor_id BIGINT -> vendors.id
  paid_date DATE
  payment_status ENUM('pending','paid','cancelled')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table funding_sources {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(100) required
  type ENUM('internal','investor','bank_loan','grant','crowdfunding','other') required
  total_budget DECIMAL(15,2)
  available_budget DECIMAL(15,2)
  start_date DATE
  end_date DATE
  interest_rate DECIMAL(5,2)
  repayment_terms TEXT
  contact_person VARCHAR(100)
  contact_email VARCHAR(100)
  contact_phone VARCHAR(20)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  status ENUM('active','pending','exhausted','closed')
  currency VARCHAR(3)
}

table funding_allocations {
  id BIGINT pk
  funding_source_id BIGINT required -> funding_sources.id
  project_id BIGINT -> projects.id
  department_id BIGINT -> departments.id
  amount DECIMAL(15,2) required
  allocation_date DATE required
  purpose TEXT
  status ENUM('planned','approved','allocated','spent','cancelled')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  approved_by_user_id BIGINT -> users.id
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table funding_thresholds {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  min_score DECIMAL(5,2) required
  max_score DECIMAL(5,2) required
  funding_recommendation TEXT required
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  approval_level ENUM('team_lead','manager','director','executive','board') required
  funding_percentage DECIMAL(5,2)
}

table budget_items {
  id BIGINT pk
  code VARCHAR(50) required
  name VARCHAR(100) required
  project_id BIGINT -> projects.id
  department_id BIGINT -> departments.id
  budget_category_id BIGINT required -> budget_categories.id
  fiscal_year INT required
  estimated_cost DECIMAL(15,2) required
  approved_cost DECIMAL(15,2)
  actual_cost DECIMAL(15,2)
  variance DECIMAL(15,2)
  variance_percentage DECIMAL(5,2)
  status ENUM('draft','submitted','approved','rejected','closed')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  approved_by_user_id BIGINT -> users.id
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table budget_categories {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  parent_category_id BIGINT -> budget_categories.id
  is_expense BOOLEAN
  ledger_account_id BIGINT -> ledger_accounts.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table ledger_accounts {
  id BIGINT pk
  account_number VARCHAR(50) unique required
  name VARCHAR(100) required
  account_type ENUM('asset','liability','equity','revenue','expense') required
  parent_account_id BIGINT -> ledger_accounts.id
  description TEXT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  balance DECIMAL(15,2)
  currency VARCHAR(3)
}

table vendors {
  id BIGINT pk
  company_name VARCHAR(255) required
  contact_name VARCHAR(100)
  email VARCHAR(100)
  phone VARCHAR(20)
  website VARCHAR(255)
  address TEXT
  tax_id VARCHAR(50)
  category ENUM('marketing','technology','office','production','consulting','other') required
  payment_terms VARCHAR(100)
  rating INT
  notes TEXT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  bank_account_details TEXT
  preferred_payment_method ENUM('bank_transfer','check','credit_card','paypal','other')
}

table invoices {
  id BIGINT pk
  invoice_number VARCHAR(50) unique required
  order_id BIGINT -> orders.id
  contact_id BIGINT required -> contacts.id
  vendor_id BIGINT -> vendors.id
  invoice_date DATE required
  due_date DATE required
  total_amount DECIMAL(15,2) required
  paid_amount DECIMAL(15,2)
  balance_due DECIMAL(15,2)
  status ENUM('draft','sent','partially_paid','paid','overdue','cancelled')
  type ENUM('sales','purchase') required
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
}

table invoice_items {
  id BIGINT pk
  invoice_id BIGINT required -> invoices.id
  product_id BIGINT -> products.id
  description VARCHAR(255) required
  quantity DECIMAL(10,2) required
  unit_price DECIMAL(15,2) required
  tax_rate DECIMAL(5,2)
  tax_amount DECIMAL(15,2)
  discount_amount DECIMAL(15,2)
  line_total DECIMAL(15,2) required
  order_item_id BIGINT -> order_items.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table financial_transactions {
  id BIGINT pk
  transaction_date TIMESTAMP required
  amount DECIMAL(15,2) required
  transaction_type ENUM('sale','purchase','payment','refund','adjustment','transfer') required
  description TEXT
  reference_type VARCHAR(50)
  reference_id BIGINT
  debit_account_id BIGINT required -> ledger_accounts.id
  credit_account_id BIGINT required -> ledger_accounts.id
  created_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  currency VARCHAR(3)
  exchange_rate DECIMAL(10,6)
  is_reconciled BOOLEAN
}

table departments {
  id BIGINT pk
  name VARCHAR(100) required
  code VARCHAR(20) unique required
  parent_department_id BIGINT -> departments.id
  manager_user_id BIGINT -> users.id
  budget_amount DECIMAL(15,2)
  fiscal_year INT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  is_active BOOLEAN
  description TEXT
}

table tax_rates {
  id BIGINT pk
  name VARCHAR(100) required
  rate DECIMAL(5,2) required
  country VARCHAR(100) required
  state VARCHAR(100)
  is_default BOOLEAN
  applies_to ENUM('product','service','all')
  effective_date DATE required
  expiration_date DATE
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table assets {
  id BIGINT pk
  name VARCHAR(255) required
  asset_type ENUM('equipment','property','vehicle','software','furniture','intellectual','other') required
  purchase_date DATE
  purchase_cost DECIMAL(15,2)
  current_value DECIMAL(15,2)
  depreciation_method ENUM('straight_line','declining_balance','units_of_production','none')
  useful_life_years INT
  salvage_value DECIMAL(15,2)
  location VARCHAR(255)
  department_id BIGINT -> departments.id
  responsible_user_id BIGINT -> users.id
  status ENUM('active','in_repair','retired','sold','lost')
  warranty_expiry_date DATE
  serial_number VARCHAR(100)
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table financial_reports {
  id BIGINT pk
  report_type ENUM('p_and_l','balance_sheet','cash_flow','budget_vs_actual','sales','tax','custom') required
  name VARCHAR(255) required
  period_start DATE required
  period_end DATE required
  generated_at TIMESTAMP required
  generated_by_user_id BIGINT required -> users.id
  report_data JSON
  summary TEXT
  is_final BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  currency VARCHAR(3)
}

table science_works {
  id BIGINT pk
  title VARCHAR(255) required
  abstract TEXT
  object TEXT
  subject TEXT
  hypothesis TEXT
  goals TEXT
  tasks TEXT
  methodology TEXT
  relevance TEXT
  novelty TEXT
  description TEXT
  sample_size INT
  year INT required
  work_period_id BIGINT -> work_periods.id
  url VARCHAR(255)
  data JSON
  work_publication_id BIGINT -> work_publications.id
  status ENUM('planning','in_progress','completed','published','archived')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  department_id BIGINT -> departments.id
  estimated_budget DECIMAL(15,2)
  actual_budget DECIMAL(15,2)
}

table work_periods {
  id BIGINT pk
  name VARCHAR(100) required
  start_year INT required
  end_year INT
  description TEXT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_authors {
  id BIGINT pk
  first_name VARCHAR(100) required
  last_name VARCHAR(100) required
  middle_name VARCHAR(100)
  birth_year INT
  death_year INT
  nationality VARCHAR(100)
  institution VARCHAR(255)
  biography TEXT
  email VARCHAR(100)
  orcid_id VARCHAR(50)
  scopus_id VARCHAR(50)
  web_of_science_id VARCHAR(50)
  google_scholar_id VARCHAR(100)
  research_areas TEXT
  profile_photo_url VARCHAR(255)
  personal_website VARCHAR(255)
  social_media_links JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  is_active BOOLEAN
}

table work_authors {
  id BIGINT pk
  science_author_id BIGINT required -> science_authors.id
  science_work_id BIGINT required -> science_works.id
  affiliation VARCHAR(255)
  role ENUM('primary','contributor','advisor','reviewer','editor') required
  contribution_description TEXT
  order_number INT required
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table work_results {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  description TEXT required
  quantitative_data TEXT
  statistical_significance DECIMAL(10,6)
  implications TEXT
  result_type ENUM('primary','secondary','unexpected','negative','inconclusive')
  verification_method TEXT
  reproducibility_steps TEXT
  data_url VARCHAR(255)
  visual_representation_url VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table work_publications {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  title VARCHAR(255) required
  journal VARCHAR(255)
  type ENUM('article','book','conference','thesis','report','patent','preprint','other') required
  year INT required
  doi VARCHAR(100)
  citation TEXT
  abstract TEXT
  keywords TEXT
  publication_date DATE
  publisher VARCHAR(255)
  volume VARCHAR(50)
  issue VARCHAR(50)
  pages VARCHAR(50)
  impact_factor DECIMAL(5,2)
  is_peer_reviewed BOOLEAN
  publication_status ENUM('submitted','under_review','accepted','published','rejected')
  url VARCHAR(255)
  pdf_url VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_discoveries {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  name VARCHAR(255) required
  description TEXT required
  significance TEXT
  discovery_date DATE
  patent_number VARCHAR(100)
  patent_filing_date DATE
  patent_approval_date DATE
  is_commercialized BOOLEAN
  commercial_value DECIMAL(15,2)
  validation_status ENUM('theoretical','experimental','peer_reviewed','widely_accepted','controversial')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table discovery_applications {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT required
  first_used_year INT
  related_discovery_id BIGINT required -> science_discoveries.id
  industry VARCHAR(100)
  use_case TEXT
  benefits TEXT
  limitations TEXT
  adoption_level ENUM('theoretical','prototype','early_adoption','mainstream','declining')
  economic_impact DECIMAL(15,2)
  societal_impact TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_methods {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT required
  first_used_year INT
  technical_details TEXT
  methodology_type ENUM('qualitative','quantitative','mixed','experimental','observational','computational','theoretical') required
  reliability_score DECIMAL(3,1)
  validity_score DECIMAL(3,1)
  advantages TEXT
  limitations TEXT
  required_equipment TEXT
  required_expertise TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table work_methods {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  science_method_id BIGINT required -> science_methods.id
  parameters TEXT
  application_details TEXT
  success_level ENUM('highly_successful','successful','neutral','problematic','unsuccessful')
  lessons_learned TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table method_parameters {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT required
  measurement_unit VARCHAR(50)
  data_type ENUM('numeric','text','boolean','datetime','enumeration','other') required
  possible_values TEXT
  default_value VARCHAR(255)
  min_value VARCHAR(50)
  max_value VARCHAR(50)
  is_required BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  science_method_id BIGINT required -> science_methods.id
}

table work_method_parameters {
  id BIGINT pk
  work_method_id BIGINT required -> work_methods.id
  method_parameter_id BIGINT required -> method_parameters.id
  typical_range VARCHAR(100)
  actual_value VARCHAR(255) required
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_equipment {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT required
  first_developed_year INT
  technical_specs TEXT
  manufacturer VARCHAR(255)
  model_number VARCHAR(100)
  calibration_requirements TEXT
  maintenance_requirements TEXT
  estimated_cost DECIMAL(15,2)
  lifespan_years INT
  power_requirements VARCHAR(100)
  size_dimensions VARCHAR(100)
  weight VARCHAR(50)
  hazard_level ENUM('none','low','medium','high','extreme')
  safety_precautions TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table work_equipment {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  science_equipment_id BIGINT required -> science_equipment.id
  usage_details TEXT
  start_date DATE
  end_date DATE
  performance_notes TEXT
  problems_encountered TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table products {
  id BIGINT pk
  sku VARCHAR(100) unique required
  name VARCHAR(255) required
  description TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  base_price DECIMAL(15,2) required
  cost_price DECIMAL(15,2)
  margin_percentage DECIMAL(5,2)
  stock_quantity INT
  details JSON
  is_active BOOLEAN
  product_category_id BIGINT -> product_categories.id
  product_line_id BIGINT -> product_lines.id
  min_stock_threshold INT
  max_stock_threshold INT
  reorder_quantity INT
  weight DECIMAL(10,2)
  weight_unit VARCHAR(10)
  dimensions VARCHAR(50)
  is_digital BOOLEAN
  is_featured BOOLEAN
  tax_rate_id BIGINT -> tax_rates.id
  warranty_period INT
  manufacturer_id BIGINT -> vendors.id
  created_by_user_id BIGINT required -> users.id
}

table product_categories {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  parent_category_id BIGINT -> product_categories.id
  is_active BOOLEAN
  display_order INT
  icon_url VARCHAR(255)
  slug VARCHAR(100) unique required
  meta_title VARCHAR(255)
  meta_description TEXT
  meta_keywords TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table product_lines {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  attributes JSON
  brand_id BIGINT -> brands.id
  launch_date DATE
  end_of_life_date DATE
  status ENUM('planning','active','deprecated','discontinued')
  target_audience_id BIGINT -> target_audiences.id
  positioning TEXT
  competitive_advantage TEXT
  pricing_strategy TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table technologies {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(255) required
  description TEXT required
  area_id BIGINT -> technical_areas.id
  maturity_level DECIMAL(3,1)
  development_status ENUM('concept','research','prototype','development','production','mature','obsolete')
  first_appeared_year INT
  inventor VARCHAR(255)
  patent_status ENUM('none','pending','granted','expired','public_domain')
  patent_number VARCHAR(100)
  license_type VARCHAR(100)
  open_source BOOLEAN
  github_url VARCHAR(255)
  documentation_url VARCHAR(255)
  use_cases TEXT
  limitations TEXT
  alternatives TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table technology_trends {
  id BIGINT pk
  technology_id BIGINT required -> technologies.id
  trend_date DATE required
  maturity_level DECIMAL(3,1)
  adoption_rate DECIMAL(5,2)
  investment_level DECIMAL(5,2)
  trend_analysis TEXT
  data_source VARCHAR(255)
  market_size DECIMAL(15,2)
  growth_rate DECIMAL(5,2)
  key_players TEXT
  geographic_distribution JSON
  industry_adoption JSON
  future_projection TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table software_projects {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  project_code VARCHAR(50) unique required
  start_date DATE required
  planned_end_date DATE
  actual_end_date DATE
  status ENUM('planning','development','testing','deployment','maintenance','completed','cancelled')
  repository_url VARCHAR(255)
  project_manager_user_id BIGINT -> users.id
  technical_lead_user_id BIGINT -> users.id
  methodology ENUM('waterfall','agile','scrum','kanban','hybrid','other')
  estimated_budget DECIMAL(15,2)
  actual_budget DECIMAL(15,2)
  client_id BIGINT -> contacts.id
  primary_technology VARCHAR(100)
  system_requirements TEXT
  success_criteria TEXT
  risk_assessment TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table software_releases {
  id BIGINT pk
  software_project_id BIGINT required -> software_projects.id
  version VARCHAR(50) required
  release_type ENUM('major','minor','patch','alpha','beta','rc') required
  release_date TIMESTAMP
  release_notes TEXT
  changelog TEXT
  build_number VARCHAR(50)
  git_commit_hash VARCHAR(100)
  artifacts_url VARCHAR(255)
  documentation_url VARCHAR(255)
  status ENUM('planned','development','testing','released','deprecated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table software_features {
  id BIGINT pk
  software_project_id BIGINT required -> software_projects.id
  name VARCHAR(100) required
  description TEXT
  priority ENUM('critical','high','medium','low')
  complexity ENUM('simple','moderate','complex','very_complex')
  estimated_effort DECIMAL(10,2)
  actual_effort DECIMAL(10,2)
  status ENUM('backlog','planning','development','testing','completed','cancelled')
  target_release_id BIGINT -> software_releases.id
  actual_release_id BIGINT -> software_releases.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  assigned_to_user_id BIGINT -> users.id
}

table api_services {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  base_url VARCHAR(255) required
  api_version VARCHAR(20) required
  documentation_url VARCHAR(255)
  swagger_url VARCHAR(255)
  authentication_type ENUM('none','api_key','oauth2','jwt','basic','other')
  status ENUM('development','testing','production','deprecated','retired')
  rate_limit INT
  responsible_user_id BIGINT -> users.id
  software_project_id BIGINT -> software_projects.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table api_endpoints {
  id BIGINT pk
  api_service_id BIGINT required -> api_services.id
  name VARCHAR(100) required
  path VARCHAR(255) required
  http_method ENUM('GET','POST','PUT','DELETE','PATCH','OPTIONS','HEAD') required
  description TEXT
  request_parameters JSON
  request_body_schema JSON
  response_schema JSON
  example_request TEXT
  example_response TEXT
  status_codes TEXT
  is_authenticated BOOLEAN
  rate_limit INT
  cache_ttl INT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table data_models {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  schema_definition JSON
  database_table VARCHAR(100)
  software_project_id BIGINT -> software_projects.id
  version VARCHAR(20) required
  status ENUM('draft','review','approved','active','deprecated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  responsible_user_id BIGINT -> users.id
}

table integration_points {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  source_system VARCHAR(100) required
  target_system VARCHAR(100) required
  integration_type ENUM('api','etl','webhook','message_queue','file_transfer','database','other') required
  data_flow_direction ENUM('one_way','bidirectional')
  frequency ENUM('real_time','hourly','daily','weekly','monthly','on_demand')
  data_volume_estimate VARCHAR(50)
  status ENUM('planning','development','testing','production','deprecated')
  security_notes TEXT
  error_handling_process TEXT
  monitoring_approach TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  responsible_user_id BIGINT -> users.id
}

table sciences {
  id BIGINT pk
  name VARCHAR(100) unique required
  description TEXT
  parent_science_id BIGINT -> sciences.id
  classification_code VARCHAR(50)
  research_areas TEXT
  historical_context TEXT
  key_theories TEXT
  methodological_approaches TEXT
  related_disciplines TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_concepts {
  id BIGINT pk
  term VARCHAR(255) required
  parent_concept_id BIGINT -> science_concepts.id
  definition TEXT required
  science_id BIGINT required -> sciences.id
  etymology TEXT
  historical_development TEXT
  usage_context TEXT
  alternative_definitions TEXT
  common_misconceptions TEXT
  see_also TEXT
  is_controversial BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table concept_links {
  id BIGINT pk
  concept_from_id BIGINT required -> science_concepts.id
  concept_to_id BIGINT required -> science_concepts.id
  relation_type ENUM('synonym','antonym','broader','narrower','related','part_of','has_part','derived_from','causes','contradicts') required
  description TEXT
  weight DECIMAL(3,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table concept_works {
  id BIGINT pk
  science_concept_id BIGINT required -> science_concepts.id
  science_work_id BIGINT required -> science_works.id
  is_primary BOOLEAN
  page VARCHAR(20)
  quote TEXT
  contribution_type ENUM('definition','refinement','critique','application','extension')
  significance ENUM('groundbreaking','major','notable','minor')
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table science_categories {
  id BIGINT pk
  science_id BIGINT required -> sciences.id
  name VARCHAR(100) required
  parent_category_id BIGINT -> science_categories.id
  description TEXT
  categorization_criteria TEXT
  examples TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table work_categories {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  science_category_id BIGINT required -> science_categories.id
  relevance_score DECIMAL(3,2)
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table analytics {
  id BIGINT pk
  campaign_id BIGINT -> campaigns.id
  channel_id BIGINT -> communication_channels.id
  stage_id BIGINT -> funnel_stages.id
  date DATE required
  impressions BIGINT
  clicks BIGINT
  conversions INT
  revenue DECIMAL(15,2)
  expenses DECIMAL(15,2)
  romi DECIMAL(10,2)
  additional_metrics JSON
  source VARCHAR(100)
  is_aggregated BOOLEAN
  data_quality_score DECIMAL(3,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table kpi_definitions {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  calculation_formula TEXT required
  measurement_unit VARCHAR(50) required
  target_values JSON
  frequency ENUM('daily','weekly','monthly','quarterly','annually')
  data_source VARCHAR(255)
  responsible_user_id BIGINT -> users.id
  department_id BIGINT -> departments.id
  is_active BOOLEAN
  weight DECIMAL(5,2)
  baseline_value DECIMAL(15,2)
  stretch_goal DECIMAL(15,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table kpi_results {
  id BIGINT pk
  kpi_id BIGINT required -> kpi_definitions.id
  date DATE required
  actual_value DECIMAL(15,2) required
  target_value DECIMAL(15,2) required
  performance_percentage DECIMAL(5,2)
  status ENUM('exceeded','achieved','partially_achieved','not_achieved') required
  notes TEXT
  data_source VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table organizational_learning {
  id BIGINT pk
  decision_id BIGINT -> strategic_decisions.id
  lesson_type ENUM('success','failure','insight','process_improvement','best_practice','innovation') required
  description TEXT required
  source VARCHAR(255)
  identified_date DATE required
  action_taken TEXT
  knowledge_category VARCHAR(100)
  project_id BIGINT -> projects.id
  department_id BIGINT -> departments.id
  impact_level ENUM('individual','team','department','organization','industry')
  potential_benefit TEXT
  implementation_status ENUM('identified','planned','implemented','verified','standardized')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table scoring_criteria {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(100) required
  description TEXT
  weight DECIMAL(5,2)
  evaluation_context ENUM('project','technology','research','product','personnel','vendor','generic')
  measurement_type ENUM('qualitative','quantitative','binary','scaled')
  scale_min INT
  scale_max INT
  is_required BOOLEAN
  formula TEXT
  data_source VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table scoring_rubrics {
  id BIGINT pk
  criteria_id BIGINT required -> scoring_criteria.id
  score_value INT required
  description TEXT required
  examples TEXT
  thresholds TEXT
  indicators TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table technical_parameters {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(100) required
  measurement_unit VARCHAR(50) required
  min_value DECIMAL(15,5)
  max_value DECIMAL(15,5)
  target_value DECIMAL(15,5)
  tolerance DECIMAL(15,5)
  description TEXT
  calculation_method TEXT
  measurement_interval VARCHAR(50)
  measurement_tool VARCHAR(100)
  is_critical BOOLEAN
  area_id BIGINT -> technical_areas.id
  product_category_id BIGINT -> product_categories.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table evaluators {
  id BIGINT pk
  code VARCHAR(50) unique required
  user_id BIGINT required -> users.id
  position VARCHAR(100) required
  expertise_areas TEXT
  qualification VARCHAR(255)
  certification TEXT
  years_of_experience INT
  evaluation_domains JSON
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table evaluations {
  id BIGINT pk
  evaluator_id BIGINT required -> evaluators.id
  entity_type ENUM('project','technology','research','product','personnel','vendor','other') required
  entity_id BIGINT required
  evaluation_date TIMESTAMP required
  overall_score DECIMAL(5,2)
  scores JSON
  strengths TEXT
  weaknesses TEXT
  recommendations TEXT
  status ENUM('draft','submitted','reviewed','approved','rejected')
  next_evaluation_date DATE
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table performance_metrics {
  id BIGINT pk
  goal_id BIGINT -> strategic_goals.id
  project_id BIGINT -> projects.id
  metric_name VARCHAR(100) required
  description TEXT
  measurement_method TEXT required
  target_value VARCHAR(100) required
  actual_value VARCHAR(100)
  frequency VARCHAR(50) required
  last_measurement DATE
  trend ENUM('improving','stable','declining','fluctuating','not_enough_data')
  historical_data JSON
  benchmark VARCHAR(100)
  data_source VARCHAR(255)
  responsible_user_id BIGINT -> users.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table quality_standards {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(100) required
  description TEXT
  standard_type ENUM('internal','industry','regulatory','international') required
  version VARCHAR(50)
  effective_date DATE required
  expiration_date DATE
  compliance_requirements TEXT
  certification_process TEXT
  audit_frequency VARCHAR(100)
  responsible_department_id BIGINT -> departments.id
  documentation_url VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table quality_assessments {
  id BIGINT pk
  standard_id BIGINT required -> quality_standards.id
  entity_type ENUM('product','process','service','department','project','organization') required
  entity_id BIGINT required
  assessment_date DATE required
  overall_score DECIMAL(5,2)
  compliance_level ENUM('full','partial','minimal','non_compliant') required
  findings TEXT
  corrective_actions TEXT
  next_assessment_date DATE
  assessor_id BIGINT required -> evaluators.id
  status ENUM('planned','in_progress','completed','verified')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table improvement_initiatives {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  initiative_type ENUM('process','product','service','organizational','cultural','technological') required
  status ENUM('proposed','approved','in_progress','completed','cancelled')
  priority ENUM('critical','high','medium','low')
  start_date DATE
  end_date DATE
  responsible_user_id BIGINT -> users.id
  department_id BIGINT -> departments.id
  expected_benefits TEXT
  actual_benefits TEXT
  budget DECIMAL(15,2)
  roi_estimate DECIMAL(5,2)
  source ENUM('assessment','audit','customer_feedback','employee_suggestion','incident','benchmark') required
  source_id BIGINT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table benchmarks {
  id BIGINT pk
  name VARCHAR(100) required
  description TEXT
  benchmark_type ENUM('internal','industry','competitor','best_in_class') required
  metric_id BIGINT -> performance_metrics.id
  benchmark_value DECIMAL(15,2) required
  benchmark_date DATE required
  source VARCHAR(255)
  confidence_level ENUM('high','medium','low')
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table customer_journeys {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  stage_id BIGINT required -> funnel_stages.id
  entered_at TIMESTAMP required
  exited_at TIMESTAMP
  status ENUM('active','completed','abandoned','on_hold')
  duration_seconds INT required
  entry_source VARCHAR(100)
  exit_reason VARCHAR(100)
  campaign_id BIGINT -> campaigns.id
  previous_stage_id BIGINT -> funnel_stages.id
  next_stage_id BIGINT -> funnel_stages.id
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table social_media_metrics {
  id BIGINT pk
  channel_id BIGINT required -> communication_channels.id
  post_id BIGINT -> social_media_posts.id
  date DATE required
  impressions INT
  reach INT
  engagement INT
  clicks INT
  shares INT
  comments INT
  likes INT
  saves INT
  followers_gain INT
  followers_lost INT
  profile_visits INT
  ctr DECIMAL(5,2)
  cpc DECIMAL(10,2)
  cpm DECIMAL(10,2)
  additional_metrics JSON
  sentiment_score DECIMAL(3,2)
  engagement_rate DECIMAL(5,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table user_behaviors {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  landing_page_id BIGINT -> landing_pages.id
  product_id BIGINT -> products.id
  event_time TIMESTAMP required
  event_type ENUM('page_view','scroll','click','hover','form_interaction','search','add_to_cart','purchase','abandon_cart','video_play','video_complete','download','registration','login','logout','share','custom') required
  event_details JSON
  session_id VARCHAR(100)
  referrer_url VARCHAR(255)
  device_type VARCHAR(50)
  browser VARCHAR(50)
  os VARCHAR(50)
  ip_address VARCHAR(45)
  user_agent TEXT
  time_spent_seconds INT
  page_url VARCHAR(255)
  utm_source VARCHAR(100)
  utm_medium VARCHAR(100)
  utm_campaign VARCHAR(100)
  created_at TIMESTAMP
}

table product_views {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  product_id BIGINT required -> products.id
  view_time TIMESTAMP required
  view_duration_seconds INT required
  source_page VARCHAR(255)
  view_details JSON
  device_type VARCHAR(50)
  session_id VARCHAR(100)
  is_first_view BOOLEAN
  is_return_view BOOLEAN
  campaign_id BIGINT -> campaigns.id
  utm_source VARCHAR(100)
  utm_medium VARCHAR(100)
  utm_campaign VARCHAR(100)
  channel_id BIGINT -> communication_channels.id
  added_to_cart BOOLEAN
  purchased BOOLEAN
  created_at TIMESTAMP
}

table customers {
  id BIGINT pk
  contact_id BIGINT unique required -> contacts.id
  company_id BIGINT -> companies.id
  first_purchase_date DATE
  last_purchase_date DATE
  total_orders INT
  total_spent DECIMAL(15,2)
  average_order_value DECIMAL(15,2)
  loyalty_points INT
  loyalty_tier VARCHAR(50)
  customer_status ENUM('active','inactive','at_risk','churned','new')
  lifetime_value DECIMAL(15,2)
  satisfaction_score DECIMAL(3,1)
  nps_score INT
  preferred_payment_method VARCHAR(50)
  preferred_shipping_method VARCHAR(50)
  marketing_preferences JSON
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table competitors {
  id BIGINT pk
  name VARCHAR(255) required
  country_of_registration VARCHAR(100)
  primary_brand VARCHAR(100)
  market_share DECIMAL(5,2)
  strengths TEXT
  weaknesses TEXT
  opportunities TEXT
  threats TEXT
  founding_year INT
  headquarters VARCHAR(255)
  employee_count INT
  annual_revenue DECIMAL(15,2)
  revenue_currency VARCHAR(3)
  public_status ENUM('public','private','subsidiary','state_owned','unknown')
  stock_symbol VARCHAR(20)
  website_url VARCHAR(255)
  social_media_presence JSON
  key_products JSON
  target_markets JSON
  last_analysis_date DATE
  competitive_position ENUM('leader','challenger','follower','niche')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table external_environments {
  id BIGINT pk
  analysis_date DATE required
  political_factors TEXT
  economic_factors TEXT
  social_factors TEXT
  technological_factors TEXT
  environmental_factors TEXT
  legal_factors TEXT
  geographical_scope VARCHAR(100)
  time_horizon VARCHAR(50)
  opportunity_score INT
  threat_score INT
  impact_matrix JSON
  action_recommendations TEXT
  next_review_date DATE
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  department_id BIGINT -> departments.id
}

table market_analyses {
  id BIGINT pk
  external_environment_id BIGINT -> external_environments.id
  market_size VARCHAR(100)
  growth_rate VARCHAR(50)
  market_trends TEXT
  customer_segments TEXT
  entry_barriers TEXT
  opportunities TEXT
  threats TEXT
  analysis_date DATE required
  market_name VARCHAR(100) required
  market_definition TEXT
  market_stage ENUM('emerging','growth','mature','declining')
  market_valuation DECIMAL(15,2)
  valuation_currency VARCHAR(3)
  key_success_factors TEXT
  profit_potential ENUM('high','medium','low')
  technological_disruption_risk ENUM('high','medium','low')
  regulatory_outlook TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table competitor_analyses {
  id BIGINT pk
  market_analysis_id BIGINT required -> market_analyses.id
  competitor_id BIGINT required -> competitors.id
  market_share VARCHAR(50)
  strengths TEXT
  weaknesses TEXT
  products_services TEXT
  pricing_strategy TEXT
  distribution_channels TEXT
  competitive_advantage TEXT
  marketing_approach TEXT
  customer_satisfaction_level VARCHAR(50)
  talent_strength VARCHAR(50)
  innovation_capacity VARCHAR(50)
  financial_stability VARCHAR(50)
  reaction_pattern TEXT
  strategic_direction TEXT
  threat_level ENUM('high','medium','low')
  recommendation_for_response TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table customer_feedback {
  id BIGINT pk
  contact_id BIGINT required -> contacts.id
  feedback_type ENUM('survey','review','support_case','social_mention','direct','focus_group','usability_test') required
  feedback_date TIMESTAMP required
  feedback_content TEXT required
  satisfaction_score DECIMAL(3,1)
  nps_score INT
  sentiment_score DECIMAL(3,2)
  product_id BIGINT -> products.id
  order_id BIGINT -> orders.id
  tags JSON
  status ENUM('new','reviewed','responded','actioned','closed')
  priority ENUM('critical','high','medium','low')
  assigned_to_user_id BIGINT -> users.id
  response_text TEXT
  responded_at TIMESTAMP
  created_at TIMESTAMP
  updated_at TIMESTAMP
  source_channel_id BIGINT -> communication_channels.id
  is_public BOOLEAN
}

table public_relations {
  id BIGINT pk
  title VARCHAR(255) required
  description TEXT
  pr_type ENUM('press_release','media_event','interview','press_conference','media_kit','news_article','opinion_piece','crisis_response','other') required
  status ENUM('planned','approved','in_progress','completed','cancelled')
  start_date TIMESTAMP
  end_date TIMESTAMP
  target_audience JSON
  key_messages TEXT
  media_outlets JSON
  spokesperson_user_id BIGINT -> users.id
  budget DECIMAL(15,2)
  expected_reach INT
  actual_reach INT
  success_metrics TEXT
  outcome TEXT
  press_release_url VARCHAR(255)
  media_coverage_urls JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  department_id BIGINT -> departments.id
  campaign_id BIGINT -> campaigns.id
}

table events {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  event_type ENUM('conference','webinar','workshop','exhibition','product_launch','networking','awards','other') required
  status ENUM('planned','open_registration','sold_out','in_progress','completed','cancelled')
  start_datetime TIMESTAMP required
  end_datetime TIMESTAMP required
  timezone VARCHAR(50)
  location_type ENUM('physical','virtual','hybrid') required
  location_details JSON
  capacity INT
  registered_attendees INT
  actual_attendees INT
  registration_url VARCHAR(255)
  event_page_url VARCHAR(255)
  target_audience JSON
  agenda JSON
  speakers JSON
  sponsors JSON
  budget DECIMAL(15,2)
  revenue DECIMAL(15,2)
  success_metrics TEXT
  feedback_summary TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  department_id BIGINT -> departments.id
  campaign_id BIGINT -> campaigns.id
}

table event_registrations {
  id BIGINT pk
  event_id BIGINT required -> events.id
  contact_id BIGINT required -> contacts.id
  registration_date TIMESTAMP required
  status ENUM('registered','confirmed','waitlisted','attended','no_show','cancelled')
  ticket_type VARCHAR(100)
  ticket_price DECIMAL(15,2)
  payment_status ENUM('pending','paid','refunded','waived')
  special_requirements TEXT
  check_in_time TIMESTAMP
  feedback_provided BOOLEAN
  feedback_score DECIMAL(3,1)
  feedback_comments TEXT
  utm_source VARCHAR(100)
  utm_medium VARCHAR(100)
  utm_campaign VARCHAR(100)
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table community_engagements {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  engagement_type ENUM('csr_initiative','charity_partnership','volunteer_program','educational_program','sustainability_initiative','community_support','other') required
  status ENUM('planned','active','completed','ongoing','cancelled')
  start_date DATE
  end_date DATE
  location VARCHAR(255)
  target_community VARCHAR(255)
  social_impact_goals TEXT
  partners JSON
  budget DECIMAL(15,2)
  actual_cost DECIMAL(15,2)
  participants_count INT
  success_metrics TEXT
  outcomes TEXT
  media_coverage TEXT
  documentation_url VARCHAR(255)
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  department_id BIGINT -> departments.id
}

table content_calendars {
  id BIGINT pk
  title VARCHAR(255) required
  description TEXT
  content_type ENUM('blog','social_post','email','video','podcast','whitepaper','case_study','newsletter','press_release','other') required
  status ENUM('planned','in_creation','review','approved','published','cancelled')
  planned_publish_date DATE
  actual_publish_date DATE
  channel_id BIGINT -> communication_channels.id
  campaign_id BIGINT -> campaigns.id
  target_audience_id BIGINT -> target_audiences.id
  content_brief TEXT
  key_messages TEXT
  content_url VARCHAR(255)
  content_metrics JSON
  assigned_to_user_id BIGINT -> users.id
  reviewer_user_id BIGINT -> users.id
  keywords TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table influencer_collaborations {
  id BIGINT pk
  influencer_name VARCHAR(255) required
  contact_id BIGINT -> contacts.id
  description TEXT
  collaboration_type ENUM('sponsored_post','affiliate','ambassador','product_review','content_creation','event_appearance','takeover','other') required
  status ENUM('negotiation','contracted','active','completed','cancelled')
  start_date DATE
  end_date DATE
  platforms JSON
  audience_size INT
  audience_demographics JSON
  engagement_rate DECIMAL(5,2)
  contract_terms TEXT
  compensation DECIMAL(15,2)
  compensation_type ENUM('monetary','product','hybrid','other')
  campaign_id BIGINT -> campaigns.id
  product_id BIGINT -> products.id
  content_brief TEXT
  deliverables TEXT
  published_content_urls JSON
  performance_metrics JSON
  roi DECIMAL(5,2)
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table audience_segmentation_analyses {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  analysis_date DATE required
  data_source VARCHAR(255)
  methodology TEXT
  segmentation_criteria JSON
  identified_segments JSON
  segment_sizes JSON
  segment_characteristics JSON
  primary_segment_id BIGINT -> market_segments.id
  opportunities TEXT
  recommendations TEXT
  next_steps TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table brand_health_metrics {
  id BIGINT pk
  brand_id BIGINT required -> brands.id
  measurement_date DATE required
  awareness_score DECIMAL(5,2)
  consideration_score DECIMAL(5,2)
  preference_score DECIMAL(5,2)
  satisfaction_score DECIMAL(5,2)
  loyalty_score DECIMAL(5,2)
  nps_score DECIMAL(5,2)
  brand_value_estimate DECIMAL(15,2)
  market_share DECIMAL(5,2)
  sentiment_score DECIMAL(3,2)
  social_mentions INT
  share_of_voice DECIMAL(5,2)
  reputation_score DECIMAL(5,2)
  survey_sample_size INT
  methodology TEXT
  insights TEXT
  action_items TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table relevance_matrices {
  id BIGINT pk
  project_id BIGINT required -> projects.id
  goal_id BIGINT required -> strategic_goals.id
  direct_relevance DECIMAL(5,2)
  indirect_relevance DECIMAL(5,2)
  time_relevance DECIMAL(5,2)
  combined_relevance DECIMAL(5,2)
  justification TEXT
  evaluator_user_id BIGINT required -> users.id
  evaluation_date DATE required
  status ENUM('draft','reviewed','approved','deprecated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table priority_calculation_logs {
  id BIGINT pk
  project_id BIGINT required -> projects.id
  calculation_date DATE required
  technical_score DECIMAL(5,2) required
  relevance_score DECIMAL(5,2) required
  resource_availability_score DECIMAL(5,2)
  risk_score DECIMAL(5,2)
  cost_benefit_score DECIMAL(5,2)
  composite_priority_score DECIMAL(5,2) required
  calculation_method TEXT
  weightings JSON
  calculated_by_user_id BIGINT required -> users.id
  priority_rank INT
  status ENUM('draft','reviewed','approved','superseded')
  comments TEXT
  created_at TIMESTAMP
}

table project_organizations {
  id BIGINT pk
  project_id BIGINT required -> projects.id
  company_id BIGINT required -> companies.id
  role ENUM('lead','partner','supplier','consultant','sponsor','regulator','customer','other') required
  involvement_start DATE required
  involvement_end DATE
  contract_id BIGINT -> contracts.id
  primary_contact_id BIGINT -> contacts.id
  responsibilities TEXT
  deliverables TEXT
  financial_contribution DECIMAL(15,2)
  status ENUM('active','inactive','pending','completed')
  performance_rating DECIMAL(3,1)
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table contracts {
  id BIGINT pk
  contract_number VARCHAR(100) unique required
  title VARCHAR(255) required
  description TEXT
  contract_type ENUM('service','product','employment','partnership','license','nda','msa','sla','other') required
  status ENUM('draft','review','approved','signed','active','completed','terminated','expired')
  company_id BIGINT required -> companies.id
  counterparty_id BIGINT required -> companies.id
  start_date DATE required
  end_date DATE
  value DECIMAL(15,2)
  currency VARCHAR(3)
  auto_renewal BOOLEAN
  renewal_terms TEXT
  termination_terms TEXT
  payment_terms TEXT
  legal_jurisdiction VARCHAR(100)
  contract_document_url VARCHAR(255)
  signed_date DATE
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  responsible_user_id BIGINT required -> users.id
  legal_reviewer_user_id BIGINT -> users.id
}

table project_statuses {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(100) required
  description TEXT
  sequence_order INT required
  color VARCHAR(20)
  icon VARCHAR(50)
  is_active BOOLEAN
  requires_approval BOOLEAN
  approver_role_id BIGINT -> roles.id
  next_possible_statuses JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table project_status_history {
  id BIGINT pk
  project_id BIGINT required -> projects.id
  status_id BIGINT required -> project_statuses.id
  changed_at TIMESTAMP required
  changed_by_user_id BIGINT required -> users.id
  reason TEXT
  comments TEXT
  duration_in_status INT
  created_at TIMESTAMP
}

table historical_patterns {
  id BIGINT pk
  code VARCHAR(50) unique required
  name VARCHAR(255) required
  pattern_type ENUM('success','failure','risk','opportunity','process','behavioral','other') required
  description TEXT
  success_rate DECIMAL(5,2)
  identified_by_user_id BIGINT required -> users.id
  identification_date DATE required
  business_area VARCHAR(100)
  recurrence_frequency VARCHAR(100)
  impact_level ENUM('low','medium','high','critical')
  source_projects JSON
  contributing_factors TEXT
  recommended_actions TEXT
  evidence TEXT
  verification_status ENUM('hypothetical','observed','verified','validated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table decision_records {
  id BIGINT pk
  project_id BIGINT -> projects.id
  decision_date DATE required
  decision_type ENUM('strategic','tactical','operational','technical','financial','personnel','other') required
  decision_summary TEXT required
  detailed_description TEXT
  decision_maker_id BIGINT required -> users.id
  context TEXT
  alternatives_considered TEXT
  decision_criteria TEXT
  impact TEXT
  risks TEXT
  implementation_plan TEXT
  status ENUM('proposed','approved','implemented','reversed','superseded')
  related_decisions JSON
  tags JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table policy_documents {
  id BIGINT pk
  document_number VARCHAR(100) unique required
  title VARCHAR(255) required
  document_type ENUM('policy','procedure','standard','guideline','regulation','instruction','manual','other') required
  description TEXT
  content TEXT
  version VARCHAR(20) required
  effective_date DATE required
  expiry_date DATE
  review_frequency VARCHAR(100)
  next_review_date DATE
  status ENUM('draft','review','approved','published','superseded','archived')
  department_id BIGINT -> departments.id
  owner_user_id BIGINT required -> users.id
  approver_user_id BIGINT -> users.id
  approved_date DATE
  document_url VARCHAR(255)
  related_policies JSON
  compliance_requirements TEXT
  audience VARCHAR(255)
  tags JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table org_structure {
  id BIGINT pk
  department_id BIGINT required -> departments.id
  parent_department_id BIGINT -> departments.id
  manager_user_id BIGINT -> users.id
  hierarchy_level INT required
  left_boundary INT required
  right_boundary INT required
  effective_date DATE required
  end_date DATE
  status ENUM('planned','active','historical')
  direct_reports_count INT
  total_headcount INT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table governance_committees {
  id BIGINT pk
  name VARCHAR(255) required
  code VARCHAR(50) unique required
  description TEXT
  committee_type ENUM('board','executive','audit','risk','compensation','technology','project','other') required
  purpose TEXT required
  authority_level TEXT
  meeting_frequency VARCHAR(100)
  charter_document_url VARCHAR(255)
  chair_user_id BIGINT required -> users.id
  secretary_user_id BIGINT -> users.id
  parent_committee_id BIGINT -> governance_committees.id
  established_date DATE required
  disbanded_date DATE
  status ENUM('active','inactive','planned','disbanded')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table committee_members {
  id BIGINT pk
  committee_id BIGINT required -> governance_committees.id
  user_id BIGINT required -> users.id
  role VARCHAR(100)
  start_date DATE required
  end_date DATE
  is_voting_member BOOLEAN
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table pattern_goal_trees {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  version VARCHAR(50) required
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
  status ENUM('draft','active','archived')
}

table pattern_tree_elements {
  id BIGINT pk
  goal_tree_id BIGINT required -> pattern_goal_trees.id
  parent_element_id BIGINT -> pattern_tree_elements.id
  element_name VARCHAR(255) required
  element_description TEXT
  element_level INT required
  left_boundary INT required
  right_boundary INT required
  importance_coefficient DECIMAL(5,2)
  technical_success_probability DECIMAL(5,2)
  readiness_level DECIMAL(3,1)
  status ENUM('proposed','evaluated','approved','implemented','deprecated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table pattern_expert_evaluations {
  id BIGINT pk
  element_id BIGINT required -> pattern_tree_elements.id
  expert_id BIGINT required -> evaluators.id
  evaluation_round INT required
  evaluation_method ENUM('simple','delphi','consensus') required
  importance_score DECIMAL(5,2)
  feasibility_score DECIMAL(5,2)
  time_estimate INT
  cost_estimate DECIMAL(15,2)
  comments TEXT
  created_at TIMESTAMP
}

table pattern_resource_allocations {
  id BIGINT pk
  goal_tree_id BIGINT required -> pattern_goal_trees.id
  budget_period VARCHAR(50) required
  total_budget DECIMAL(15,2) required
  allocation_status ENUM('draft','proposed','approved','implemented')
  allocation_date DATE required
  approved_by_user_id BIGINT -> users.id
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table pattern_element_allocations {
  id BIGINT pk
  resource_allocation_id BIGINT required -> pattern_resource_allocations.id
  element_id BIGINT required -> pattern_tree_elements.id
  allocated_amount DECIMAL(15,2) required
  priority_score DECIMAL(5,2) required
  created_at TIMESTAMP
}

table brand_dimension_strategies {
  id BIGINT pk
  brand_id BIGINT required -> brands.id
  dimension_type ENUM('functional','social','mental','spiritual') required
  strategy_title VARCHAR(255) required
  strategy_description TEXT
  key_metrics JSON
  implementation_plan TEXT
  current_status ENUM('planned','in_progress','implemented','evaluating','optimizing')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table brand_dimension_touchpoints {
  id BIGINT pk
  brand_dimension_strategy_id BIGINT required -> brand_dimension_strategies.id
  touchpoint_name VARCHAR(100) required
  touchpoint_type ENUM('website','product','service','communication','staff','environment','social_media','other') required
  implementation_details TEXT
  status ENUM('planned','active','inactive')
  metrics_and_kpis JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table neurophotinic_products {
  id BIGINT pk
  product_id BIGINT required -> products.id
  neural_entrainment_type ENUM('audio','visual','combined','other') required
  frequency_range VARCHAR(100)
  therapeutic_purpose TEXT
  clinical_validation_status ENUM('theoretical','laboratory','clinical_trials','validated','approved')
  safety_level ENUM('general_public','supervised_use','professional_only','research_only') required
  contraindications TEXT
  recommended_usage_protocol TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table neural_entrainment_sessions {
  id BIGINT pk
  neurophotinic_product_id BIGINT required -> neurophotinic_products.id
  protocol_name VARCHAR(255) required
  session_duration INT required
  frequency_pattern TEXT
  intensity_profile TEXT
  target_brain_state TEXT
  expected_outcomes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table payment_gateways {
  id BIGINT pk
  gateway_name VARCHAR(100) required
  gateway_type ENUM('acquiring','payment_processor','wallet','cryptocurrency','other') required
  api_credentials JSON
  commission_structure JSON
  status ENUM('active','inactive','testing','deprecated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table payment_flows {
  id BIGINT pk
  flow_name VARCHAR(255) required
  product_id BIGINT -> products.id
  funnel_stage_id BIGINT -> funnel_stages.id
  payment_gateway_id BIGINT required -> payment_gateways.id
  payment_type ENUM('one_time','subscription','installment','freemium','donation') required
  amount_strategy ENUM('fixed','dynamic','tiered','pay_what_you_want') required
  default_amount DECIMAL(15,2)
  currency VARCHAR(3)
  pricing_rules JSON
  success_redirect_url VARCHAR(255)
  failure_redirect_url VARCHAR(255)
  notification_settings JSON
  analytics_tracking_code VARCHAR(255)
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table electronic_money_pipeline {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  start_trigger_type ENUM('user_action','scheduled','external_event','manual','payment_completion') required
  trigger_configuration JSON
  currency_flow_path JSON
  revenue_distribution_rules JSON
  tax_handling_strategy TEXT
  fee_handling_strategy TEXT
  accounting_integration_details JSON
  status ENUM('draft','active','paused','archived')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table financial_pipelines {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  status ENUM('active','inactive','testing','archived')
  created_at TIMESTAMP
  updated_at TIMESTAMP
  created_by_user_id BIGINT required -> users.id
}

table pipeline_stages {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  stage_name VARCHAR(100) required
  stage_order INT required
  stage_type ENUM('revenue_collection','fund_allocation','cost_coverage','profit_distribution','reinvestment') required
  processing_rules JSON required
  approval_requirements JSON
  automation_level ENUM('manual','semi_automated','fully_automated')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table revenue_streams {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  stream_name VARCHAR(100) required
  source_type ENUM('product_sales','subscriptions','licensing','grants','investments','royalties','consulting','other') required
  product_id BIGINT -> products.id
  payment_gateway_id BIGINT -> payment_gateways.id
  revenue_allocation_rules JSON
  taxation_rules JSON
  accounting_codes JSON
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table cost_centers {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  center_name VARCHAR(100) required
  center_type ENUM('research','development','production','marketing','sales','administration','infrastructure','other') required
  department_id BIGINT -> departments.id
  budget_allocation_percentage DECIMAL(5,2)
  dynamic_allocation_rules JSON
  minimum_funding DECIMAL(15,2)
  optimal_funding DECIMAL(15,2)
  expense_categories JSON
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table investment_pools {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  pool_name VARCHAR(100) required
  purpose_type ENUM('r_and_d','equipment','marketing','expansion','reserve','innovation','other') required
  allocation_percentage DECIMAL(5,2)
  target_amount DECIMAL(15,2)
  current_amount DECIMAL(15,2)
  investment_criteria JSON
  roi_expectations JSON
  risk_profile ENUM('low','medium','high')
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table pipeline_financial_transactions {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  stage_id BIGINT required -> pipeline_stages.id
  transaction_type ENUM('revenue','expense','transfer','allocation','reinvestment','distribution') required
  amount DECIMAL(15,2) required
  currency VARCHAR(3)
  source_id BIGINT
  source_type VARCHAR(50)
  destination_id BIGINT
  destination_type VARCHAR(50)
  transaction_date TIMESTAMP required
  status ENUM('pending','processing','completed','failed','reversed')
  reference_number VARCHAR(100)
  description TEXT
  metadata JSON
  created_at TIMESTAMP
}

table financial_automation_rules {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  rule_name VARCHAR(100) required
  trigger_type ENUM('schedule','threshold','event','manual','algorithm') required
  trigger_conditions JSON
  actions JSON
  priority INT
  is_active BOOLEAN
  last_triggered_at TIMESTAMP
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table financial_metrics {
  id BIGINT pk
  pipeline_id BIGINT required -> financial_pipelines.id
  metric_name VARCHAR(100) required
  metric_type ENUM('revenue','cost','profit','roi','efficiency','velocity','distribution','other') required
  calculation_formula TEXT
  measurement_unit VARCHAR(50)
  target_value DECIMAL(15,2)
  current_value DECIMAL(15,2)
  measurement_period ENUM('daily','weekly','monthly','quarterly','annually')
  last_updated TIMESTAMP
  visualization_settings JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table monetization_models {
  id BIGINT pk
  model_name VARCHAR(100) required
  description TEXT
  applicable_product_types JSON
  revenue_mechanism TEXT
  value_delivery_method TEXT
  payment_structure JSON
  typical_metrics JSON
  success_factors TEXT
  risk_factors TEXT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table product_monetization_strategies {
  id BIGINT pk
  product_id BIGINT required -> products.id
  monetization_model_id BIGINT required -> monetization_models.id
  primary_revenue_stream_id BIGINT -> revenue_streams.id
  implementation_details TEXT
  pricing_strategy TEXT
  market_positioning TEXT
  customer_acquisition_cost DECIMAL(15,2)
  expected_customer_lifetime_value DECIMAL(15,2)
  payback_period INT
  breakeven_point DECIMAL(15,2)
  target_profit_margin DECIMAL(5,2)
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table intellectual_property_assets {
  id BIGINT pk
  asset_name VARCHAR(255) required
  asset_type ENUM('patent','copyright','trademark','trade_secret','know_how','database_right','other') required
  reference_number VARCHAR(100)
  jurisdiction VARCHAR(100)
  filing_date DATE
  grant_date DATE
  expiration_date DATE
  inventors JSON
  owners JSON
  legal_status ENUM('pending','registered','granted','maintained','abandoned','expired','disputed')
  scope_of_protection TEXT
  related_science_work_id BIGINT -> science_works.id
  commercialization_status ENUM('not_commercialized','licensing','direct_use','joint_venture','spin_off','sale')
  estimated_value DECIMAL(15,2)
  valuation_date DATE
  valuation_method VARCHAR(100)
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table licensing_agreements {
  id BIGINT pk
  ip_asset_id BIGINT required -> intellectual_property_assets.id
  licensee_id BIGINT required -> companies.id
  agreement_type ENUM('exclusive','non_exclusive','sole','cross','sublicensable') required
  territory VARCHAR(255)
  field_of_use TEXT
  start_date DATE required
  end_date DATE
  royalty_type ENUM('percentage','fixed','minimum_guarantee','milestone','hybrid','other') required
  royalty_terms JSON
  upfront_payment DECIMAL(15,2)
  maintenance_fees JSON
  performance_obligations TEXT
  audit_rights TEXT
  termination_conditions TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table commercialization_pathways {
  id BIGINT pk
  name VARCHAR(255) required
  description TEXT
  total_estimated_time INT
  total_estimated_budget DECIMAL(15,2)
  success_probability DECIMAL(5,2)
  risk_assessment TEXT
  resource_requirements JSON
  critical_success_factors TEXT
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table commercialization_stages {
  id BIGINT pk
  pathway_id BIGINT required -> commercialization_pathways.id
  stage_name VARCHAR(100) required
  stage_order INT required
  description TEXT
  expected_duration INT
  estimated_cost DECIMAL(15,2)
  key_activities TEXT
  deliverables TEXT
  required_expertise JSON
  exit_criteria TEXT
  dependency_type ENUM('linear','flexible','milestone_based')
  dependency_conditions JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table commercialization_projects {
  id BIGINT pk
  science_work_id BIGINT required -> science_works.id
  pathway_id BIGINT required -> commercialization_pathways.id
  project_name VARCHAR(255) required
  project_manager_user_id BIGINT required -> users.id
  current_stage_id BIGINT -> commercialization_stages.id
  start_date DATE required
  planned_end_date DATE
  actual_end_date DATE
  status ENUM('planning','in_progress','on_hold','completed','cancelled')
  progress_percentage DECIMAL(5,2)
  budget DECIMAL(15,2)
  actual_spend DECIMAL(15,2)
  target_product_id BIGINT -> products.id
  risks_and_challenges TEXT
  success_metrics JSON
  resource_allocation_plan JSON
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table stage_activities {
  id BIGINT pk
  project_id BIGINT required -> commercialization_projects.id
  stage_id BIGINT required -> commercialization_stages.id
  activity_name VARCHAR(100) required
  description TEXT
  start_date DATE
  end_date DATE
  status ENUM('planned','in_progress','completed','blocked','cancelled')
  responsible_user_id BIGINT -> users.id
  estimated_hours DECIMAL(8,2)
  actual_hours DECIMAL(8,2)
  dependencies JSON
  output_deliverables TEXT
  notes TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table technology_readiness_assessments {
  id BIGINT pk
  project_id BIGINT required -> commercialization_projects.id
  assessment_date DATE required
  trl_level INT required
  evidence TEXT
  assessor_user_id BIGINT required -> users.id
  gaps_identified TEXT
  recommended_actions TEXT
  next_assessment_date DATE
  created_at TIMESTAMP
}

table pricing_strategies {
  id BIGINT pk
  strategy_name VARCHAR(100) required
  description TEXT
  suitable_for_product_types JSON
  pricing_formula TEXT
  key_variables JSON
  advantages TEXT
  limitations TEXT
  market_conditions TEXT
  example_implementation TEXT
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table product_pricing_models {
  id BIGINT pk
  product_id BIGINT required -> products.id
  pricing_strategy_id BIGINT required -> pricing_strategies.id
  base_price DECIMAL(15,2) required
  currency VARCHAR(3)
  price_components JSON
  cost_breakdown JSON
  margin_percentage DECIMAL(5,2)
  discount_policy JSON
  price_tiers JSON
  dynamic_pricing_rules JSON
  price_review_frequency VARCHAR(50)
  last_review_date DATE
  next_review_date DATE
  market_positioning TEXT
  competitor_price_analysis TEXT
  price_elasticity_estimate DECIMAL(5,2)
  is_active BOOLEAN
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table value_based_pricing_factors {
  id BIGINT pk
  product_pricing_id BIGINT required -> product_pricing_models.id
  factor_name VARCHAR(100) required
  factor_description TEXT
  measurement_method TEXT
  quantitative_value DECIMAL(15,2)
  qualitative_value TEXT
  customer_segment_id BIGINT -> market_segments.id
  relative_importance DECIMAL(5,2)
  evidence_source TEXT
  impact_on_price DECIMAL(15,2)
  created_at TIMESTAMP
  updated_at TIMESTAMP
}

table pricing_experiments {
  id BIGINT pk
  product_id BIGINT required -> products.id
  experiment_name VARCHAR(255) required
  description TEXT
  start_date DATE required
  end_date DATE
  control_price DECIMAL(15,2) required
  test_prices JSON
  target_metrics JSON
  segmentation_criteria JSON
  results JSON
  conclusions TEXT
  implemented_changes TEXT
  status ENUM('planned','in_progress','completed','analyzed','implemented')
  created_at TIMESTAMP
  updated_at TIMESTAMP
}
` as const;
