/** AREA: STYLIST CODER MODEL -> AUTO-GENERATED */
export {
	FOUNDATION_DEPTH_THRESHOLDS,
	FOUNDATION_SEMANTIC_ZOOM_STAGES,
	PRESENTATION_MODE,
	TOKEN_FOUNDATION_AXES,
	TOKEN_FOUNDATION_AXIS_DIRECTIONS,
	TOKEN_TIER_CONTENT
} from './array';
export {
	RECORD_DENSITY,
	RECORD_FRAME,
	RECORD_LAYER,
	RECORD_LEVEL,
	RECORD_SHAPE,
	RECORD_SIZE
} from './record';
export {
	DEFAULT_FOUNDATION_CAMERA,
	FOCUS_DURATION_MS,
	FOUNDATION_DEPTH_RANGE
} from './value';
